### PR TITLE
Format

### PR DESCRIPTION
**Pull request by vmuriart**
General clean-up.

- Cleaned Whitespace
- Removed extra files
- Format/Clean-up `README`
- Added sample `coverageConfig.json`

### CODE REVIEW

**Comment by thomasrockhu** [comment]
@vmuriart I can't for the life of me get this to pass the tests (years later). Any chance you could take a look here?

**Comment by vmuriart** [comment]
its been a while... let me take a look

**Comment by vmuriart** [comment]
Looks like the problem is with the `FluentAssertions` `6.0.0` not being compatible with Mono. Have you tried it w the old version?

**Comment by thomasrockhu** [comment]
@vmuriart, I feel like I'm at another roadblock. Any tips here with running [instrument](https://travis-ci.org/github/codecov/example-csharp-sharpcover/builds/722170187#L1435)?

**Comment by thomasrockhu** [comment]
@vmuriart I'm going to close this out because I don't think I have the ability to get this merged in if it's still failing tests. Feel free to re-open if you are able to get this to a passing state, and I will merge.

**Pull request closed without merging**
